[versions]
# Fabric Properties
minecraft = "1.21.11"
fabric-mappings = "1.21.11+build.4"
fabric-loader = "0.18.4"
fabric-api = "0.141.1+1.21.11"
fabric-loom = "1.14.10"
# owo-lib = "0.12.15.4+1.21"

# Additional Dependencies from your build.gradle
devauth = "1.2.2"
discord-ipc = "0.8.2"
jackson = "2.14.2"
shadow = "8.1.1"
log4j = "2.25.2"
reflections = "0.10.2"
javassist = "3.29.0-GA"
commands = "1.0.18"

[libraries]
# Minecraft
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-mappings" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
commands = { group = "com.mojang", name = "brigadier", version.ref = "commands"}
javassist = { group = "org.javassist", name = "javassist", version.ref = "javassist" }
# owo-lib = { group = "io.wispforest", name = "owo-lib", version.ref = "owo-lib" }

# Additional Dependencies
dev-auth = { group = "me.djtheredstoner", name = "DevAuth-fabric", version.ref = "devauth" }
discord-ipc = { group = "io.github.CDAGaming", name = "DiscordIPC", version.ref = "discord-ipc" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
log4j = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
reflections = { group = "org.reflections", name = "reflections", version.ref = "reflections" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }