[versions]
# Fabric Properties
minecraft = "1.21.11"
fabric-mappings = "1.21.11+build.4"
fabric-loader = "0.18.4"
fabric-api = "0.141.1+1.21.11"
fabric-loom = "1.14.10"

# Additional Dependencies from your build.gradle
devauth = "1.2.2"
discord-ipc = "0.8.2"
jackson = "2.14.2"
shadow = "8.1.1"
log4j = "2.25.2"
reflections = "0.10.2"
javassist = "3.29.0-GA"
commands = "1.0.18"
junixsocket = "2.10.1"
mockito = "5.+"
junit = "6.0.2"

[libraries]
# Minecraft
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-mappings" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
commands = { group = "com.mojang", name = "brigadier", version.ref = "commands"}
javassist = { group = "org.javassist", name = "javassist", version.ref = "javassist" }

# Additional Dependencies
dev-auth = { group = "me.djtheredstoner", name = "DevAuth-fabric", version.ref = "devauth" }
discord-ipc = { group = "io.github.CDAGaming", name = "DiscordIPC", version.ref = "discord-ipc" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
log4j = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
reflections = { group = "org.reflections", name = "reflections", version.ref = "reflections" }

junixsocket-core = { group = "com.kohlschutter.junixsocket", name = "junixsocket-core", version.ref = "junixsocket" }
junixsocket-common = { group = "com.kohlschutter.junixsocket", name = "junixsocket-common", version.ref = "junixsocket" }
junixsocket-native-common = { group = "com.kohlschutter.junixsocket", name = "junixsocket-native-common", version.ref = "junixsocket" }

mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }