[versions]
# Fabric Properties
minecraft = "1.21.10"
fabric-mappings = "1.21.10+build.3"
fabric-loader = "0.18.1"
fabric-api = "0.138.3+1.21.10"
fabric-loom = "1.13.6"

# Additional Dependencies from your build.gradle
devauth = "1.2.1"
discord-ipc = "0.8.2"
jackson = "2.14.2"
shadow = "8.1.1"
log4j = "2.25.2"

[libraries]
# Minecraft
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-mappings = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-mappings" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

# Additional Dependencies
dev-auth = { group = "me.djtheredstoner", name = "DevAuth-fabric", version.ref = "devauth" }
discord-ipc = { group = "io.github.CDAGaming", name = "DiscordIPC", version.ref = "discord-ipc" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
log4j = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
maven-publish = { id = "maven-publish" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }