name: "Publish on Modrinth"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JAVA_VERSION: 21

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v6.0.1

      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Extract Version
        id: get_version
        run: |
          MOD_VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2 | xargs)
          echo "MOD_VERSION=$MOD_VERSION" >> $GITHUB_ENV
               
          MOD_NAME=$(grep '^name=' gradle.properties | cut -d'=' -f2 | xargs)
          echo "MOD_NAME=$MOD_NAME" >> $GITHUB_ENV
          
          MINECRAFT_VERSION=$(sed -n 's/^minecraft = "\(.*\)"/\1/p' gradle/libs.versions.toml | xargs)
          echo "MINECRAFT_VERSION=$MINECRAFT_VERSION" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew clean build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: "${{env.MOD_NAME}}"
          version: "${{env.MOD_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}